"""
Module containing all relevant elements generated by a `gedcom.parser.Parser`.
An element represents a line within GEDCOM data.
"""

__all__ = [
    "element",
    "family",
    "file",
    "individual",
    "object",
    "root"
]
