"""
Module containing all relevant elements generated by a `gedcom.parser.Parser`.
An element represents a line within GEDCOM data.

Most element types defined in the GEDCOM spec do not have classes here - only those
that have methods that shouldn't live in the more generic Element class.
"""